import type { EventType, Stage, Status } from "../../generated/prisma/client";

export const timelineEventByStage: Record<Stage, EventType> = {
  APPLIED: "APPLIED",
  ASSESSMENT: "ASSESSMENT_COMPLETED",
  FIRST_INTERVIEW: "FIRST_INTERVIEW_COMPLETED",
  SECOND_INTERVIEW: "SECOND_INTERVIEW_COMPLETED",
  THIRD_INTERVIEW: "THIRD_INTERVIEW_COMPLETED",
  HR_INTERVIEW: "HR_INTERVIEW_COMPLETED",
  OFFER: "OFFER_RECEIVED",
  REJECTED: "REJECTED",
};

export const stageByTimelineEvent: Record<EventType, Stage> = {
  APPLIED: "APPLIED",
  ASSESSMENT_COMPLETED: "ASSESSMENT",
  FIRST_INTERVIEW_COMPLETED: "FIRST_INTERVIEW",
  SECOND_INTERVIEW_COMPLETED: "SECOND_INTERVIEW",
  THIRD_INTERVIEW_COMPLETED: "THIRD_INTERVIEW",
  HR_INTERVIEW_COMPLETED: "HR_INTERVIEW",
  OFFER_RECEIVED: "OFFER",
  REJECTED: "REJECTED",
};

export function statusForStage(stage: Stage): Status {
  return stage === "REJECTED" ? "FAILED" : "PENDING";
}
